-- Migration number: 0003 	 2026-02-01T03:22:33.721Z
-- Seed assessment products, versions, and sample ACSF questions

-- ============================================
-- Step 1: Add missing assessment products
-- ============================================
INSERT OR IGNORE INTO assessment_products (product_id, name, aqf_level, stream, active, version) VALUES
  ('prod-cert1-trade', 'Certificate I - Trade Stream', 'Certificate I', 'Trade', 1, '1.0'),
  ('prod-cert2-trade', 'Certificate II - Trade Stream', 'Certificate II', 'Trade', 1, '1.0'),
  ('prod-cert4-trade', 'Certificate IV - Trade Stream', 'Certificate IV', 'Trade', 1, '1.0'),
  ('prod-cert1-community', 'Certificate I - Community Services', 'Certificate I', 'Community Services', 1, '1.0'),
  ('prod-cert2-community', 'Certificate II - Community Services', 'Certificate II', 'Community Services', 1, '1.0'),
  ('prod-cert3-community', 'Certificate III - Community Services', 'Certificate III', 'Community Services', 1, '1.0'),
  ('prod-cert4-community', 'Certificate IV - Community Services', 'Certificate IV', 'Community Services', 1, '1.0');

-- ============================================
-- Step 2: Create assessment versions
-- ============================================
INSERT OR IGNORE INTO assessment_versions (version_id, product_id, version_number, is_active, description, created_at) VALUES
  ('ver-cert1-trade-v1', 'prod-cert1-trade', 'v1.0', 1, 'Initial LLND assessment for Certificate I Trade students', unixepoch()),
  ('ver-cert2-trade-v1', 'prod-cert2-trade', 'v1.0', 1, 'Initial LLND assessment for Certificate II Trade students', unixepoch()),
  ('ver-cert3-trade-v1', 'prod-cert3-trade', 'v1.0', 1, 'Initial LLND assessment for Certificate III Trade students', unixepoch()),
  ('ver-cert4-trade-v1', 'prod-cert4-trade', 'v1.0', 1, 'Initial LLND assessment for Certificate IV Trade students', unixepoch()),
  ('ver-cert1-community-v1', 'prod-cert1-community', 'v1.0', 1, 'Initial LLND assessment for Certificate I Community Services students', unixepoch()),
  ('ver-cert2-community-v1', 'prod-cert2-community', 'v1.0', 1, 'Initial LLND assessment for Certificate II Community Services students', unixepoch()),
  ('ver-cert3-community-v1', 'prod-cert3-community', 'v1.0', 1, 'Initial LLND assessment for Certificate III Community Services students', unixepoch()),
  ('ver-cert4-community-v1', 'prod-cert4-community', 'v1.0', 1, 'Initial LLND assessment for Certificate IV Community Services students', unixepoch());

-- ============================================
-- Step 3: Seed Questions - Certificate I Trade
-- ============================================
-- Reading questions (ACSF Level 1 difficulty)
INSERT INTO questions (question_id, product_id, version_id, text, type, options, domain, order_index, correct_response, weight, question_text, question_type, acsf_domain, correct_answer, points_possible, acsf_skill, acsf_level) VALUES
  ('q-c1t-r1', 'prod-cert1-trade', 'ver-cert1-trade-v1', 'What does the safety sign with a hard hat mean?', 'multiple_choice', '["Wear safety boots", "Wear a hard hat", "Wear safety glasses", "No entry"]', 'Reading', 1, 'Wear a hard hat', 1.0, 'What does the safety sign with a hard hat mean?', 'multiple_choice', 'Reading', 'Wear a hard hat', 1.0, 'Identifies symbols and signs', 1),
  ('q-c1t-r2', 'prod-cert1-trade', 'ver-cert1-trade-v1', 'Where do you find the emergency exit in your workshop?', 'short_answer', null, 'Reading', 2, 'Near the back door', 1.0, 'Where do you find the emergency exit in your workshop?', 'short_answer', 'Reading', 'Near the back door', 1.0, 'Locates specific information', 1),
  ('q-c1t-r3', 'prod-cert1-trade', 'ver-cert1-trade-v1', 'A toolbox label says "DO NOT USE". Can you use the tools?', 'true_false', '["True", "False"]', 'Reading', 3, 'False', 1.0, 'A toolbox label says "DO NOT USE". Can you use the tools?', 'true_false', 'Reading', 'False', 1.0, 'Follows simple written instructions', 1),
  ('q-c1t-r4', 'prod-cert1-trade', 'ver-cert1-trade-v1', 'What information is on a safety data sheet (SDS)?', 'multiple_choice', '["Product hazards", "Employee names", "Room temperature", "Tool prices"]', 'Reading', 4, 'Product hazards', 1.0, 'What information is on a safety data sheet (SDS)?', 'multiple_choice', 'Reading', 'Product hazards', 1.0, 'Recognises purpose of common texts', 1);

-- Writing questions (ACSF Level 1)
INSERT INTO questions (question_id, product_id, version_id, text, type, options, domain, order_index, correct_response, weight, question_text, question_type, acsf_domain, correct_answer, points_possible, acsf_skill, acsf_level) VALUES
  ('q-c1t-w1', 'prod-cert1-trade', 'ver-cert1-trade-v1', 'Write your name on a sign-in sheet when you arrive at work.', 'short_answer', null, 'Writing', 5, 'John Smith', 1.0, 'Write your name on a sign-in sheet when you arrive at work.', 'short_answer', 'Writing', 'John Smith', 1.0, 'Writes own name and details', 1),
  ('q-c1t-w2', 'prod-cert1-trade', 'ver-cert1-trade-v1', 'Complete this sentence: "I need to order more ____ for the job."', 'short_answer', null, 'Writing', 6, 'materials', 1.0, 'Complete this sentence: "I need to order more ____ for the job."', 'short_answer', 'Writing', 'materials', 1.0, 'Completes simple forms', 1),
  ('q-c1t-w3', 'prod-cert1-trade', 'ver-cert1-trade-v1', 'Write a short message to your supervisor: You will be 30 minutes late tomorrow.', 'short_answer', null, 'Writing', 7, 'I will be 30 minutes late tomorrow', 1.0, 'Write a short message to your supervisor: You will be 30 minutes late tomorrow.', 'short_answer', 'Writing', 'I will be 30 minutes late tomorrow', 1.0, 'Writes simple messages', 1);

-- Oral Communication questions (ACSF Level 1)
INSERT INTO questions (question_id, product_id, version_id, text, type, options, domain, order_index, correct_response, weight, question_text, question_type, acsf_domain, correct_answer, points_possible, acsf_skill, acsf_level) VALUES
  ('q-c1t-o1', 'prod-cert1-trade', 'ver-cert1-trade-v1', 'Your supervisor asks you to get a hammer. What do you do?', 'multiple_choice', '["Ignore them", "Get the hammer", "Ask someone else", "Leave work"]', 'Oral Communication', 8, 'Get the hammer', 1.0, 'Your supervisor asks you to get a hammer. What do you do?', 'multiple_choice', 'Oral Communication', 'Get the hammer', 1.0, 'Follows simple verbal instructions', 1),
  ('q-c1t-o2', 'prod-cert1-trade', 'ver-cert1-trade-v1', 'If you don''t understand instructions, what should you say?', 'multiple_choice', '["Nothing", "Can you repeat that please?", "I quit", "That''s wrong"]', 'Oral Communication', 9, 'Can you repeat that please?', 1.0, 'If you don''t understand instructions, what should you say?', 'multiple_choice', 'Oral Communication', 'Can you repeat that please?', 1.0, 'Asks for clarification', 1);

-- Numeracy questions (ACSF Level 1)
INSERT INTO questions (question_id, product_id, version_id, text, type, options, domain, order_index, correct_response, weight, question_text, question_type, acsf_domain, correct_answer, points_possible, acsf_skill, acsf_level) VALUES
  ('q-c1t-n1', 'prod-cert1-trade', 'ver-cert1-trade-v1', 'You have 5 screws. You use 2. How many do you have left?', 'multiple_choice', '["2", "3", "5", "7"]', 'Numeracy', 10, '3', 1.0, 'You have 5 screws. You use 2. How many do you have left?', 'multiple_choice', 'Numeracy', '3', 1.0, 'Basic subtraction', 1),
  ('q-c1t-n2', 'prod-cert1-trade', 'ver-cert1-trade-v1', 'What time is it when the clock shows 3:00?', 'multiple_choice', '["2 o''clock", "3 o''clock", "4 o''clock", "5 o''clock"]', 'Numeracy', 11, '3 o''clock', 1.0, 'What time is it when the clock shows 3:00?', 'multiple_choice', 'Numeracy', '3 o''clock', 1.0, 'Tells time', 1),
  ('q-c1t-n3', 'prod-cert1-trade', 'ver-cert1-trade-v1', 'How many centimeters are in 1 meter?', 'multiple_choice', '["10", "50", "100", "1000"]', 'Numeracy', 12, '100', 1.0, 'How many centimeters are in 1 meter?', 'multiple_choice', 'Numeracy', '100', 1.0, 'Basic measurement units', 1),
  ('q-c1t-n4', 'prod-cert1-trade', 'ver-cert1-trade-v1', 'If you work 8 hours per day for 2 days, how many hours is that?', 'short_answer', null, 'Numeracy', 13, '16', 1.0, 'If you work 8 hours per day for 2 days, how many hours is that?', 'short_answer', 'Numeracy', '16', 1.0, 'Simple multiplication', 1);

-- Digital Literacy questions (ACSF Level 1)
INSERT INTO questions (question_id, product_id, version_id, text, type, options, domain, order_index, correct_response, weight, question_text, question_type, acsf_domain, correct_answer, points_possible, acsf_skill, acsf_level) VALUES
  ('q-c1t-d1', 'prod-cert1-trade', 'ver-cert1-trade-v1', 'How do you turn on a computer?', 'multiple_choice', '["Press any key", "Press the power button", "Unplug it", "Close the screen"]', 'Digital Literacy', 14, 'Press the power button', 1.0, 'How do you turn on a computer?', 'multiple_choice', 'Digital Literacy', 'Press the power button', 1.0, 'Basic device operation', 1),
  ('q-c1t-d2', 'prod-cert1-trade', 'ver-cert1-trade-v1', 'Where do you type a website address in a web browser?', 'multiple_choice', '["In the document", "In the address bar", "In settings", "In the trash"]', 'Digital Literacy', 15, 'In the address bar', 1.0, 'Where do you type a website address in a web browser?', 'multiple_choice', 'Digital Literacy', 'In the address bar', 1.0, 'Basic internet navigation', 1);

-- ============================================
-- Step 4: Certificate II Trade Questions (ACSF Level 2)
-- ============================================
INSERT INTO questions (question_id, product_id, version_id, text, type, options, domain, order_index, correct_response, weight, question_text, question_type, acsf_domain, correct_answer, points_possible, acsf_skill, acsf_level) VALUES
  -- Reading
  ('q-c2t-r1', 'prod-cert2-trade', 'ver-cert2-trade-v1', 'Read this work instruction: "Measure twice, cut once." What does this mean?', 'multiple_choice', '["Cut two times", "Check measurements before cutting", "Use two tools", "Measure after cutting"]', 'Reading', 1, 'Check measurements before cutting', 1.0, 'Read this work instruction: "Measure twice, cut once." What does this mean?', 'multiple_choice', 'Reading', 'Check measurements before cutting', 1.0, 'Interprets routine instructions', 2),
  ('q-c2t-r2', 'prod-cert2-trade', 'ver-cert2-trade-v1', 'A material safety data sheet says "Store in cool, dry place." Where should you NOT store the material?', 'multiple_choice', '["In a cupboard", "In direct sunlight", "On a shelf", "In the storeroom"]', 'Reading', 2, 'In direct sunlight', 1.0, 'A material safety data sheet says "Store in cool, dry place." Where should you NOT store the material?', 'multiple_choice', 'Reading', 'In direct sunlight', 1.0, 'Draws meaning from workplace texts', 2),
  ('q-c2t-r3', 'prod-cert2-trade', 'ver-cert2-trade-v1', 'According to the duty roster, who is working the afternoon shift on Tuesday?', 'short_answer', null, 'Reading', 3, 'Sarah', 1.0, 'According to the duty roster, who is working the afternoon shift on Tuesday?', 'short_answer', 'Reading', 'Sarah', 1.0, 'Locates information in tables', 2),
  ('q-c2t-r4', 'prod-cert2-trade', 'ver-cert2-trade-v1', 'What is the main purpose of a job card?', 'multiple_choice', '["To pay employees", "To record work completed", "To order materials", "To hire staff"]', 'Reading', 4, 'To record work completed', 1.0, 'What is the main purpose of a job card?', 'multiple_choice', 'Reading', 'To record work completed', 1.0, 'Understands purpose of workplace documents', 2),
  -- Writing
  ('q-c2t-w1', 'prod-cert2-trade', 'ver-cert2-trade-v1', 'Fill out a materials request form: Item needed, quantity, and reason.', 'short_answer', null, 'Writing', 5, '10 meters of electrical cable for workshop wiring', 1.0, 'Fill out a materials request form: Item needed, quantity, and reason.', 'short_answer', 'Writing', '10 meters of electrical cable for workshop wiring', 1.0, 'Completes workplace forms', 2),
  ('q-c2t-w2', 'prod-cert2-trade', 'ver-cert2-trade-v1', 'Write a brief note to your team about a tool that is broken and needs repair.', 'short_answer', null, 'Writing', 6, 'The angle grinder is broken and needs to be repaired before we can continue', 1.0, 'Write a brief note to your team about a tool that is broken and needs repair.', 'short_answer', 'Writing', 'The angle grinder is broken and needs to be repaired before we can continue', 1.0, 'Writes routine workplace messages', 2),
  ('q-c2t-w3', 'prod-cert2-trade', 'ver-cert2-trade-v1', 'List the steps you would take to safely lock out a machine before maintenance.', 'short_answer', null, 'Writing', 7, 'Turn off machine, disconnect power, attach lockout tag, verify power is off', 1.0, 'List the steps you would take to safely lock out a machine before maintenance.', 'short_answer', 'Writing', 'Turn off machine, disconnect power, attach lockout tag, verify power is off', 1.0, 'Writes simple procedures', 2),
  -- Oral Communication
  ('q-c2t-o1', 'prod-cert2-trade', 'ver-cert2-trade-v1', 'During a team meeting, what is the best way to share an idea?', 'multiple_choice', '["Interrupt others", "Wait for your turn to speak", "Whisper to your neighbour", "Send a text message"]', 'Oral Communication', 8, 'Wait for your turn to speak', 1.0, 'During a team meeting, what is the best way to share an idea?', 'multiple_choice', 'Oral Communication', 'Wait for your turn to speak', 1.0, 'Participates in group discussions', 2),
  ('q-c2t-o2', 'prod-cert2-trade', 'ver-cert2-trade-v1', 'How should you report a safety hazard to your supervisor?', 'multiple_choice', '["Don''t report it", "Tell them clearly and immediately", "Write it in your diary", "Tell other workers only"]', 'Oral Communication', 9, 'Tell them clearly and immediately', 1.0, 'How should you report a safety hazard to your supervisor?', 'multiple_choice', 'Oral Communication', 'Tell them clearly and immediately', 1.0, 'Communicates workplace information', 2),
  -- Numeracy
  ('q-c2t-n1', 'prod-cert2-trade', 'ver-cert2-trade-v1', 'A job requires 3.5 meters of material. You have 10 meters. How much will be left?', 'short_answer', null, 'Numeracy', 10, '6.5', 1.0, 'A job requires 3.5 meters of material. You have 10 meters. How much will be left?', 'short_answer', 'Numeracy', '6.5', 1.0, 'Decimal subtraction', 2),
  ('q-c2t-n2', 'prod-cert2-trade', 'ver-cert2-trade-v1', 'If paint costs $45 per 4-litre tin, how much for 8 litres?', 'short_answer', null, 'Numeracy', 11, '90', 1.0, 'If paint costs $45 per 4-litre tin, how much for 8 litres?', 'short_answer', 'Numeracy', '90', 1.0, 'Simple proportion calculations', 2),
  ('q-c2t-n3', 'prod-cert2-trade', 'ver-cert2-trade-v1', 'Convert 2.5 hours to minutes.', 'short_answer', null, 'Numeracy', 12, '150', 1.0, 'Convert 2.5 hours to minutes.', 'short_answer', 'Numeracy', '150', 1.0, 'Time conversions', 2),
  ('q-c2t-n4', 'prod-cert2-trade', 'ver-cert2-trade-v1', 'A rectangular room is 4m × 3m. What is the area?', 'short_answer', null, 'Numeracy', 13, '12', 1.0, 'A rectangular room is 4m × 3m. What is the area?', 'short_answer', 'Numeracy', '12', 1.0, 'Basic area calculation', 2),
  -- Digital Literacy
  ('q-c2t-d1', 'prod-cert2-trade', 'ver-cert2-trade-v1', 'How do you save a document you are working on?', 'multiple_choice', '["Close the window", "Click File > Save", "Turn off computer", "Print it"]', 'Digital Literacy', 14, 'Click File > Save', 1.0, 'How do you save a document you are working on?', 'multiple_choice', 'Digital Literacy', 'Click File > Save', 1.0, 'Uses basic software features', 2),
  ('q-c2t-d2', 'prod-cert2-trade', 'ver-cert2-trade-v1', 'What should you do before clicking on an email attachment from an unknown sender?', 'multiple_choice', '["Click it immediately", "Delete the email", "Forward it to everyone", "Save it to desktop"]', 'Digital Literacy', 15, 'Delete the email', 1.0, 'What should you do before clicking on an email attachment from an unknown sender?', 'multiple_choice', 'Digital Literacy', 'Delete the email', 1.0, 'Recognises digital safety risks', 2);

-- ============================================
-- Step 5: Certificate III Trade Questions (ACSF Level 3)
-- ============================================
INSERT INTO questions (question_id, product_id, version_id, text, type, options, domain, order_index, correct_response, weight, question_text, question_type, acsf_domain, correct_answer, points_possible, acsf_skill, acsf_level) VALUES
  -- Reading
  ('q-c3t-r1', 'prod-cert3-trade', 'ver-cert3-trade-v1', 'Analyse this workplace policy: "All electrical work must comply with AS/NZS 3000." What does this require?', 'multiple_choice', '["Any electrical work is acceptable", "Work must meet the Australian/NZ electrical standard", "Only use imported materials", "Electrical work is prohibited"]', 'Reading', 1, 'Work must meet the Australian/NZ electrical standard', 1.0, 'Analyse this workplace policy: "All electrical work must comply with AS/NZS 3000." What does this require?', 'multiple_choice', 'Reading', 'Work must meet the Australian/NZ electrical standard', 1.0, 'Interprets workplace regulations', 3),
  ('q-c3t-r2', 'prod-cert3-trade', 'ver-cert3-trade-v1', 'Read the project specification and identify what quality standards apply to welding work.', 'short_answer', null, 'Reading', 2, 'AS/NZS 1554.1 and visual inspection for defects', 1.0, 'Read the project specification and identify what quality standards apply to welding work.', 'short_answer', 'Reading', 'AS/NZS 1554.1 and visual inspection for defects', 1.0, 'Extracts technical requirements', 3),
  ('q-c3t-r3', 'prod-cert3-trade', 'ver-cert3-trade-v1', 'Compare two product data sheets and determine which material has better corrosion resistance.', 'short_answer', null, 'Reading', 3, 'Material B has better corrosion resistance due to higher coating thickness', 1.0, 'Compare two product data sheets and determine which material has better corrosion resistance.', 'short_answer', 'Reading', 'Material B has better corrosion resistance due to higher coating thickness', 1.0, 'Compares technical information', 3),
  ('q-c3t-r4', 'prod-cert3-trade', 'ver-cert3-trade-v1', 'Based on the maintenance log, when is the next service due for Equipment ID #4521?', 'short_answer', null, 'Reading', 4, 'Next service due in 2 weeks based on 200-hour service interval', 1.0, 'Based on the maintenance log, when is the next service due for Equipment ID #4521?', 'short_answer', 'Reading', 'Next service due in 2 weeks based on 200-hour service interval', 1.0, 'Interprets maintenance schedules', 3),
  -- Writing
  ('q-c3t-w1', 'prod-cert3-trade', 'ver-cert3-trade-v1', 'Write an incident report describing a near-miss event in the workshop, including what happened, why, and recommendations.', 'short_answer', null, 'Writing', 5, 'Near miss occurred when forklift reversed without spotter. Poor visibility was the cause. Recommend mandatory spotter use and reversing alarms.', 1.0, 'Write an incident report describing a near-miss event in the workshop, including what happened, why, and recommendations.', 'short_answer', 'Writing', 'Near miss occurred when forklift reversed without spotter. Poor visibility was the cause. Recommend mandatory spotter use and reversing alarms.', 1.0, 'Writes detailed incident reports', 3),
  ('q-c3t-w2', 'prod-cert3-trade', 'ver-cert3-trade-v1', 'Document the steps to perform a pre-start inspection on a piece of machinery, including safety checks.', 'short_answer', null, 'Writing', 6, 'Visual inspection for damage, check fluid levels, test emergency stops, verify guards in place, check for leaks, test operation', 1.0, 'Document the steps to perform a pre-start inspection on a piece of machinery, including safety checks.', 'short_answer', 'Writing', 'Visual inspection for damage, check fluid levels, test emergency stops, verify guards in place, check for leaks, test operation', 1.0, 'Writes technical procedures', 3),
  ('q-c3t-w3', 'prod-cert3-trade', 'ver-cert3-trade-v1', 'Prepare a written quotation for a client that includes materials, labour hours, and total cost with GST.', 'short_answer', null, 'Writing', 7, 'Materials $500, Labour 8 hours at $85/hr = $680, Subtotal $1180, GST $118, Total $1298', 1.0, 'Prepare a written quotation for a client that includes materials, labour hours, and total cost with GST.', 'short_answer', 'Writing', 'Materials $500, Labour 8 hours at $85/hr = $680, Subtotal $1180, GST $118, Total $1298', 1.0, 'Prepares business documents', 3),
  -- Oral Communication
  ('q-c3t-o1', 'prod-cert3-trade', 'ver-cert3-trade-v1', 'You need to explain a complex technical issue to a client who has no technical background. What approach is best?', 'multiple_choice', '["Use technical jargon", "Explain using simple terms and examples", "Tell them to ask someone else", "Refuse to explain"]', 'Oral Communication', 8, 'Explain using simple terms and examples', 1.0, 'You need to explain a complex technical issue to a client who has no technical background. What approach is best?', 'multiple_choice', 'Oral Communication', 'Explain using simple terms and examples', 1.0, 'Adapts communication to audience', 3),
  ('q-c3t-o2', 'prod-cert3-trade', 'ver-cert3-trade-v1', 'During a toolbox talk, how should you present safety information to ensure understanding?', 'multiple_choice', '["Speak quickly to save time", "Use clear language, check understanding, provide examples", "Hand out a document and walk away", "Only tell the supervisor"]', 'Oral Communication', 9, 'Use clear language, check understanding, provide examples', 1.0, 'During a toolbox talk, how should you present safety information to ensure understanding?', 'multiple_choice', 'Oral Communication', 'Use clear language, check understanding, provide examples', 1.0, 'Presents information effectively', 3),
  -- Numeracy
  ('q-c3t-n1', 'prod-cert3-trade', 'ver-cert3-trade-v1', 'Calculate the volume of concrete needed for a slab 6m × 4m × 0.1m thick.', 'short_answer', null, 'Numeracy', 10, '2.4', 1.0, 'Calculate the volume of concrete needed for a slab 6m × 4m × 0.1m thick.', 'short_answer', 'Numeracy', '2.4', 1.0, 'Volume calculations', 3),
  ('q-c3t-n2', 'prod-cert3-trade', 'ver-cert3-trade-v1', 'If a project budget is $15,000 and you have spent $9,450, what percentage of the budget remains?', 'short_answer', null, 'Numeracy', 11, '37', 1.0, 'If a project budget is $15,000 and you have spent $9,450, what percentage of the budget remains?', 'short_answer', 'Numeracy', '37', 1.0, 'Percentage calculations', 3),
  ('q-c3t-n3', 'prod-cert3-trade', 'ver-cert3-trade-v1', 'A pipe has an outside diameter of 50mm and wall thickness of 3mm. What is the inside diameter?', 'short_answer', null, 'Numeracy', 12, '44', 1.0, 'A pipe has an outside diameter of 50mm and wall thickness of 3mm. What is the inside diameter?', 'short_answer', 'Numeracy', '44', 1.0, 'Applied measurement', 3),
  ('q-c3t-n4', 'prod-cert3-trade', 'ver-cert3-trade-v1', 'Using the scale 1:50, if a wall measures 80mm on the plan, what is the actual wall length in meters?', 'short_answer', null, 'Numeracy', 13, '4', 1.0, 'Using the scale 1:50, if a wall measures 80mm on the plan, what is the actual wall length in meters?', 'short_answer', 'Numeracy', '4', 1.0, 'Scale and ratio', 3),
  -- Digital Literacy
  ('q-c3t-d1', 'prod-cert3-trade', 'ver-cert3-trade-v1', 'You need to create a spreadsheet to track job costs. Which software would you use?', 'multiple_choice', '["Microsoft Word", "Microsoft Excel", "Notepad", "Web browser"]', 'Digital Literacy', 14, 'Microsoft Excel', 1.0, 'You need to create a spreadsheet to track job costs. Which software would you use?', 'multiple_choice', 'Digital Literacy', 'Microsoft Excel', 1.0, 'Selects appropriate applications', 3),
  ('q-c3t-d2', 'prod-cert3-trade', 'ver-cert3-trade-v1', 'How would you share a large technical drawing file (50MB) with a client via email?', 'multiple_choice', '["Attach it directly to email", "Use a cloud sharing service like OneDrive or Dropbox", "Print it and post it", "Don''t share it"]', 'Digital Literacy', 15, 'Use a cloud sharing service like OneDrive or Dropbox', 1.0, 'How would you share a large technical drawing file (50MB) with a client via email?', 'multiple_choice', 'Digital Literacy', 'Use a cloud sharing service like OneDrive or Dropbox', 1.0, 'Uses digital tools effectively', 3);

-- ============================================
-- Step 6: Certificate IV Trade Questions (ACSF Level 4)
-- ============================================
INSERT INTO questions (question_id, product_id, version_id, text, type, options, domain, order_index, correct_response, weight, question_text, question_type, acsf_domain, correct_answer, points_possible, acsf_skill, acsf_level) VALUES
  -- Reading
  ('q-c4t-r1', 'prod-cert4-trade', 'ver-cert4-trade-v1', 'Critically evaluate this OH&S policy for potential gaps in risk management procedures.', 'short_answer', null, 'Reading', 1, 'The policy lacks specific controls for confined space entry and does not address emergency response procedures adequately', 1.0, 'Critically evaluate this OH&S policy for potential gaps in risk management procedures.', 'short_answer', 'Reading', 'The policy lacks specific controls for confined space entry and does not address emergency response procedures adequately', 1.0, 'Critically analyses complex texts', 4),
  ('q-c4t-r2', 'prod-cert4-trade', 'ver-cert4-trade-v1', 'Interpret engineering drawings to identify load-bearing requirements and structural specifications.', 'short_answer', null, 'Reading', 2, 'Load-bearing capacity is 25kN/m2 as per structural engineer notation, with reinforcement specified in detail A-3', 1.0, 'Interpret engineering drawings to identify load-bearing requirements and structural specifications.', 'short_answer', 'Reading', 'Load-bearing capacity is 25kN/m2 as per structural engineer notation, with reinforcement specified in detail A-3', 1.0, 'Interprets technical drawings', 4),
  ('q-c4t-r3', 'prod-cert4-trade', 'ver-cert4-trade-v1', 'Review the project contract and identify clauses related to variation claims and liquidated damages.', 'short_answer', null, 'Reading', 3, 'Clause 15 covers variations requiring written approval. Clause 22 specifies $500/day liquidated damages for delays beyond practical completion', 1.0, 'Review the project contract and identify clauses related to variation claims and liquidated damages.', 'short_answer', 'Reading', 'Clause 15 covers variations requiring written approval. Clause 22 specifies $500/day liquidated damages for delays beyond practical completion', 1.0, 'Analyses contractual documents', 4),
  ('q-c4t-r4', 'prod-cert4-trade', 'ver-cert4-trade-v1', 'Compare Australian Standards AS 3600 and AS 4100 - what types of structures does each cover?', 'short_answer', null, 'Reading', 4, 'AS 3600 covers concrete structures, AS 4100 covers steel structures. Both provide design and construction requirements for their respective materials', 1.0, 'Compare Australian Standards AS 3600 and AS 4100 - what types of structures does each cover?', 'short_answer', 'Reading', 'AS 3600 covers concrete structures, AS 4100 covers steel structures. Both provide design and construction requirements for their respective materials', 1.0, 'Compares technical standards', 4),
  -- Writing
  ('q-c4t-w1', 'prod-cert4-trade', 'ver-cert4-trade-v1', 'Prepare a comprehensive method statement for high-risk construction work including plant, personnel, safety controls, and sequences.', 'short_answer', null, 'Writing', 5, 'Method: Excavation using 20T excavator. Personnel: 1 operator, 1 spotter, 1 supervisor. Controls: Exclusion zones, service location, shoring system, daily inspections. Sequence: Locate services, establish barriers, excavate in 1m lifts, install shoring progressively.', 1.0, 'Prepare a comprehensive method statement for high-risk construction work including plant, personnel, safety controls, and sequences.', 'short_answer', 'Writing', 'Method: Excavation using 20T excavator. Personnel: 1 operator, 1 spotter, 1 supervisor. Controls: Exclusion zones, service location, shoring system, daily inspections. Sequence: Locate services, establish barriers, excavate in 1m lifts, install shoring progressively.', 1.0, 'Develops technical documentation', 4),
  ('q-c4t-w2', 'prod-cert4-trade', 'ver-cert4-trade-v1', 'Write a formal project progress report addressing schedule, budget variance, quality issues, and risk mitigation.', 'short_answer', null, 'Writing', 6, 'Project 85% complete, 2 weeks behind schedule due to weather delays. Budget variance +3% due to material price increases. Quality audit passed. Mitigation: Additional crew allocated, value engineering options being explored.', 1.0, 'Write a formal project progress report addressing schedule, budget variance, quality issues, and risk mitigation.', 'short_answer', 'Writing', 'Project 85% complete, 2 weeks behind schedule due to weather delays. Budget variance +3% due to material price increases. Quality audit passed. Mitigation: Additional crew allocated, value engineering options being explored.', 1.0, 'Writes formal business reports', 4),
  ('q-c4t-w3', 'prod-cert4-trade', 'ver-cert4-trade-v1', 'Draft a non-conformance report that analyses root cause and proposes corrective and preventive actions.', 'short_answer', null, 'Writing', 7, 'Non-conformance: Concrete strength test failed (25MPa vs 32MPa specified). Root cause: Incorrect water/cement ratio. Corrective action: Remove and replace affected concrete. Preventive action: Implement batch testing protocol and supplier audits.', 1.0, 'Draft a non-conformance report that analyses root cause and proposes corrective and preventive actions.', 'short_answer', 'Writing', 'Non-conformance: Concrete strength test failed (25MPa vs 32MPa specified). Root cause: Incorrect water/cement ratio. Corrective action: Remove and replace affected concrete. Preventive action: Implement batch testing protocol and supplier audits.', 1.0, 'Writes analytical reports', 4),
  -- Oral Communication
  ('q-c4t-o1', 'prod-cert4-trade', 'ver-cert4-trade-v1', 'You are leading a site safety induction for a new subcontractor team. What elements must you cover?', 'short_answer', null, 'Oral Communication', 8, 'Site hazards, emergency procedures, PPE requirements, permit systems, reporting procedures, environmental controls, and specific work method statements', 1.0, 'You are leading a site safety induction for a new subcontractor team. What elements must you cover?', 'short_answer', 'Oral Communication', 'Site hazards, emergency procedures, PPE requirements, permit systems, reporting procedures, environmental controls, and specific work method statements', 1.0, 'Delivers formal presentations', 4),
  ('q-c4t-o2', 'prod-cert4-trade', 'ver-cert4-trade-v1', 'During a client meeting, how do you handle a dispute about scope of work?', 'multiple_choice', '["Argue your position forcefully", "Refer to contract documents, discuss professionally, seek mutually acceptable solution", "Walk out of the meeting", "Agree to everything the client says"]', 'Oral Communication', 9, 'Refer to contract documents, discuss professionally, seek mutually acceptable solution', 1.0, 'During a client meeting, how do you handle a dispute about scope of work?', 'multiple_choice', 'Oral Communication', 'Refer to contract documents, discuss professionally, seek mutually acceptable solution', 1.0, 'Negotiates and resolves issues', 4),
  -- Numeracy
  ('q-c4t-n1', 'prod-cert4-trade', 'ver-cert4-trade-v1', 'Calculate the labour cost for a project: 3 workers for 40 hours at $45/hr, 1 supervisor for 40 hours at $65/hr, plus 25% for overheads and profit.', 'short_answer', null, 'Numeracy', 10, '10125', 1.0, 'Calculate the labour cost for a project: 3 workers for 40 hours at $45/hr, 1 supervisor for 40 hours at $65/hr, plus 25% for overheads and profit.', 'short_answer', 'Numeracy', '10125', 1.0, 'Complex cost calculations', 4),
  ('q-c4t-n2', 'prod-cert4-trade', 'ver-cert4-trade-v1', 'A steel beam deflects 15mm under load. If the maximum allowable deflection is span/250 and the span is 6m, is this acceptable?', 'short_answer', null, 'Numeracy', 11, 'No, maximum allowable is 24mm (6000/250), actual deflection of 15mm is acceptable', 1.0, 'A steel beam deflects 15mm under load. If the maximum allowable deflection is span/250 and the span is 6m, is this acceptable?', 'short_answer', 'Numeracy', 'No, maximum allowable is 24mm (6000/250), actual deflection of 15mm is acceptable', 1.0, 'Engineering calculations', 4),
  ('q-c4t-n3', 'prod-cert4-trade', 'ver-cert4-trade-v1', 'Calculate the critical path duration: Task A (3 days), Task B (5 days, depends on A), Task C (4 days, depends on A), Task D (2 days, depends on B and C).', 'short_answer', null, 'Numeracy', 12, '10', 1.0, 'Calculate the critical path duration: Task A (3 days), Task B (5 days, depends on A), Task C (4 days, depends on A), Task D (2 days, depends on B and C).', 'short_answer', 'Numeracy', '10', 1.0, 'Project scheduling mathematics', 4),
  ('q-c4t-n4', 'prod-cert4-trade', 'ver-cert4-trade-v1', 'If material wastage is typically 8% and you need 250m² of finished area, how much material should you order?', 'short_answer', null, 'Numeracy', 13, '270', 1.0, 'If material wastage is typically 8% and you need 250m² of finished area, how much material should you order?', 'short_answer', 'Numeracy', '270', 1.0, 'Wastage calculations', 4),
  -- Digital Literacy
  ('q-c4t-d1', 'prod-cert4-trade', 'ver-cert4-trade-v1', 'Which software would you use to create a project schedule with dependencies, resources, and critical path analysis?', 'multiple_choice', '["Microsoft Word", "Microsoft Project or Primavera", "Calculator", "Email"]', 'Digital Literacy', 14, 'Microsoft Project or Primavera', 1.0, 'Which software would you use to create a project schedule with dependencies, resources, and critical path analysis?', 'multiple_choice', 'Digital Literacy', 'Microsoft Project or Primavera', 1.0, 'Uses specialized project software', 4),
  ('q-c4t-d2', 'prod-cert4-trade', 'ver-cert4-trade-v1', 'How would you implement version control for project documentation across multiple team members?', 'multiple_choice', '["Email files back and forth", "Use collaborative platform like SharePoint with version history", "Keep files on personal computer", "Print everything"]', 'Digital Literacy', 15, 'Use collaborative platform like SharePoint with version history', 1.0, 'How would you implement version control for project documentation across multiple team members?', 'multiple_choice', 'Digital Literacy', 'Use collaborative platform like SharePoint with version history', 1.0, 'Manages digital workflows', 4);

-- ============================================
-- Step 7: Certificate I Community Services (ACSF Level 1)
-- ============================================
INSERT INTO questions (question_id, product_id, version_id, text, type, options, domain, order_index, correct_response, weight, question_text, question_type, acsf_domain, correct_answer, points_possible, acsf_skill, acsf_level) VALUES
  -- Reading
  ('q-c1c-r1', 'prod-cert1-community', 'ver-cert1-community-v1', 'What does a "STOP" sign mean in a care facility?', 'multiple_choice', '["Go faster", "Stop and wait", "Turn around", "Keep walking"]', 'Reading', 1, 'Stop and wait', 1.0, 'What does a "STOP" sign mean in a care facility?', 'multiple_choice', 'Reading', 'Stop and wait', 1.0, 'Identifies common signs', 1),
  ('q-c1c-r2', 'prod-cert1-community', 'ver-cert1-community-v1', 'Where is the first aid kit located?', 'short_answer', null, 'Reading', 2, 'In the staff room cupboard', 1.0, 'Where is the first aid kit located?', 'short_answer', 'Reading', 'In the staff room cupboard', 1.0, 'Locates important items', 1),
  ('q-c1c-r3', 'prod-cert1-community', 'ver-cert1-community-v1', 'A resident care plan says "assist with meals". Should you feed the resident?', 'true_false', '["True", "False"]', 'Reading', 3, 'True', 1.0, 'A resident care plan says "assist with meals". Should you feed the resident?', 'true_false', 'Reading', 'True', 1.0, 'Follows simple care instructions', 1),
  ('q-c1c-r4', 'prod-cert1-community', 'ver-cert1-community-v1', 'What is a medication chart used for?', 'multiple_choice', '["Ordering food", "Recording medications given", "Booking holidays", "Calling families"]', 'Reading', 4, 'Recording medications given', 1.0, 'What is a medication chart used for?', 'multiple_choice', 'Reading', 'Recording medications given', 1.0, 'Understands basic care documents', 1),
  -- Writing
  ('q-c1c-w1', 'prod-cert1-community', 'ver-cert1-community-v1', 'Sign your name on the staff attendance sheet.', 'short_answer', null, 'Writing', 5, 'Mary Jones', 1.0, 'Sign your name on the staff attendance sheet.', 'short_answer', 'Writing', 'Mary Jones', 1.0, 'Writes own name', 1),
  ('q-c1c-w2', 'prod-cert1-community', 'ver-cert1-community-v1', 'Write the date on a progress note: Today is Monday 15th March.', 'short_answer', null, 'Writing', 6, '15/03', 1.0, 'Write the date on a progress note: Today is Monday 15th March.', 'short_answer', 'Writing', '15/03', 1.0, 'Writes simple dates', 1),
  ('q-c1c-w3', 'prod-cert1-community', 'ver-cert1-community-v1', 'Complete this sentence: The resident needs help with ____.', 'short_answer', null, 'Writing', 7, 'walking', 1.0, 'Complete this sentence: The resident needs help with ____.', 'short_answer', 'Writing', 'walking', 1.0, 'Completes simple sentences', 1),
  -- Oral Communication
  ('q-c1c-o1', 'prod-cert1-community', 'ver-cert1-community-v1', 'A resident asks for water. What do you do?', 'multiple_choice', '["Ignore them", "Get them water", "Tell them to wait all day", "Leave the room"]', 'Oral Communication', 8, 'Get them water', 1.0, 'A resident asks for water. What do you do?', 'multiple_choice', 'Oral Communication', 'Get them water', 1.0, 'Responds to simple requests', 1),
  ('q-c1c-o2', 'prod-cert1-community', 'ver-cert1-community-v1', 'How should you greet a resident in the morning?', 'multiple_choice', '["Don''t greet them", "Say "Good morning"", "Ignore them", "Shout at them"]', 'Oral Communication', 9, 'Say "Good morning"', 1.0, 'How should you greet a resident in the morning?', 'multiple_choice', 'Oral Communication', 'Say "Good morning"', 1.0, 'Uses polite greetings', 1),
  -- Numeracy
  ('q-c1c-n1', 'prod-cert1-community', 'ver-cert1-community-v1', 'A resident needs 2 tablets in the morning and 1 at night. How many tablets per day?', 'short_answer', null, 'Numeracy', 10, '3', 1.0, 'A resident needs 2 tablets in the morning and 1 at night. How many tablets per day?', 'short_answer', 'Numeracy', '3', 1.0, 'Simple addition', 1),
  ('q-c1c-n2', 'prod-cert1-community', 'ver-cert1-community-v1', 'What time is lunch if the clock shows 12:00?', 'multiple_choice', '["Breakfast time", "Lunch time", "Dinner time", "Bed time"]', 'Numeracy', 11, 'Lunch time', 1.0, 'What time is lunch if the clock shows 12:00?', 'multiple_choice', 'Numeracy', 'Lunch time', 1.0, 'Tells time for daily routines', 1),
  ('q-c1c-n3', 'prod-cert1-community', 'ver-cert1-community-v1', 'Count 5 cups for 5 residents. Is this enough?', 'true_false', '["True", "False"]', 'Numeracy', 12, 'True', 1.0, 'Count 5 cups for 5 residents. Is this enough?', 'true_false', 'Numeracy', 'True', 1.0, 'One-to-one correspondence', 1),
  ('q-c1c-n4', 'prod-cert1-community', 'ver-cert1-community-v1', 'A resident temperature is 37°C. Is this normal body temperature?', 'true_false', '["True", "False"]', 'Numeracy', 13, 'True', 1.0, 'A resident temperature is 37°C. Is this normal body temperature?', 'true_false', 'Numeracy', 'True', 1.0, 'Recognises normal measurements', 1),
  -- Digital Literacy
  ('q-c1c-d1', 'prod-cert1-community', 'ver-cert1-community-v1', 'How do you answer a phone call?', 'multiple_choice', '["Don''t answer it", "Pick up and say hello", "Hang up immediately", "Throw the phone"]', 'Digital Literacy', 14, 'Pick up and say hello', 1.0, 'How do you answer a phone call?', 'multiple_choice', 'Digital Literacy', 'Pick up and say hello', 1.0, 'Uses basic phone', 1),
  ('q-c1c-d2', 'prod-cert1-community', 'ver-cert1-community-v1', 'Where do you click to open an app on a tablet?', 'multiple_choice', '["On the icon", "On the edge", "On the back", "Don''t click"]', 'Digital Literacy', 15, 'On the icon', 1.0, 'Where do you click to open an app on a tablet?', 'multiple_choice', 'Digital Literacy', 'On the icon', 1.0, 'Basic device operation', 1);

-- ============================================
-- Step 8: Certificate II Community Services (ACSF Level 2)
-- ============================================
INSERT INTO questions (question_id, product_id, version_id, text, type, options, domain, order_index, correct_response, weight, question_text, question_type, acsf_domain, correct_answer, points_possible, acsf_skill, acsf_level) VALUES
  -- Reading
  ('q-c2c-r1', 'prod-cert2-community', 'ver-cert2-community-v1', 'Read this care plan note: "Client prefers shower in evening". When should you assist with showering?', 'multiple_choice', '["Morning", "Evening", "Never", "Any time"]', 'Reading', 1, 'Evening', 1.0, 'Read this care plan note: "Client prefers shower in evening". When should you assist with showering?', 'multiple_choice', 'Reading', 'Evening', 1.0, 'Interprets routine care instructions', 2),
  ('q-c2c-r2', 'prod-cert2-community', 'ver-cert2-community-v1', 'A dietary requirement says "Gluten-free diet". Which food should you avoid?', 'multiple_choice', '["Rice", "Bread", "Fruit", "Vegetables"]', 'Reading', 2, 'Bread', 1.0, 'A dietary requirement says "Gluten-free diet". Which food should you avoid?', 'multiple_choice', 'Reading', 'Bread', 1.0, 'Understands dietary requirements', 2),
  ('q-c2c-r3', 'prod-cert2-community', 'ver-cert2-community-v1', 'Check the staff roster. Who is working the night shift on Wednesday?', 'short_answer', null, 'Reading', 3, 'Ahmed', 1.0, 'Check the staff roster. Who is working the night shift on Wednesday?', 'short_answer', 'Reading', 'Ahmed', 1.0, 'Reads timetables', 2),
  ('q-c2c-r4', 'prod-cert2-community', 'ver-cert2-community-v1', 'What is the purpose of an incident report?', 'multiple_choice', '["To blame staff", "To document and prevent incidents", "To punish residents", "To fill time"]', 'Reading', 4, 'To document and prevent incidents', 1.0, 'What is the purpose of an incident report?', 'multiple_choice', 'Reading', 'To document and prevent incidents', 1.0, 'Understands workplace documents', 2),
  -- Writing
  ('q-c2c-w1', 'prod-cert2-community', 'ver-cert2-community-v1', 'Write a progress note: Client ate half of lunch and drank one glass of water.', 'short_answer', null, 'Writing', 5, 'Client consumed 50% of meal and 250ml water at lunch', 1.0, 'Write a progress note: Client ate half of lunch and drank one glass of water.', 'short_answer', 'Writing', 'Client consumed 50% of meal and 250ml water at lunch', 1.0, 'Writes care observations', 2),
  ('q-c2c-w2', 'prod-cert2-community', 'ver-cert2-community-v1', 'Complete a handover note about a resident who had a fall but is now okay.', 'short_answer', null, 'Writing', 6, 'Resident had minor fall at 2pm, no injuries, vitals normal, family notified', 1.0, 'Complete a handover note about a resident who had a fall but is now okay.', 'short_answer', 'Writing', 'Resident had minor fall at 2pm, no injuries, vitals normal, family notified', 1.0, 'Writes handover information', 2),
  ('q-c2c-w3', 'prod-cert2-community', 'ver-cert2-community-v1', 'List the steps to help a resident get dressed in the morning.', 'short_answer', null, 'Writing', 7, 'Ask preference, provide privacy, assist with buttons, check comfort, offer shoes', 1.0, 'List the steps to help a resident get dressed in the morning.', 'short_answer', 'Writing', 'Ask preference, provide privacy, assist with buttons, check comfort, offer shoes', 1.0, 'Writes simple procedures', 2),
  -- Oral Communication
  ('q-c2c-o1', 'prod-cert2-community', 'ver-cert2-community-v1', 'A family member asks about their relative. What should you do?', 'multiple_choice', '["Tell them everything", "Refer to qualified staff and maintain privacy", "Ignore them", "Make up information"]', 'Oral Communication', 8, 'Refer to qualified staff and maintain privacy', 1.0, 'A family member asks about their relative. What should you do?', 'multiple_choice', 'Oral Communication', 'Refer to qualified staff and maintain privacy', 1.0, 'Maintains confidentiality', 2),
  ('q-c2c-o2', 'prod-cert2-community', 'ver-cert2-community-v1', 'How do you report a change in a client''s condition to your supervisor?', 'multiple_choice', '["Don''t report it", "Report clearly and promptly with specific observations", "Wait until next week", "Tell other residents"]', 'Oral Communication', 9, 'Report clearly and promptly with specific observations', 1.0, 'How do you report a change in a client''s condition to your supervisor?', 'multiple_choice', 'Oral Communication', 'Report clearly and promptly with specific observations', 1.0, 'Reports changes effectively', 2),
  -- Numeracy
  ('q-c2c-n1', 'prod-cert2-community', 'ver-cert2-community-v1', 'A client needs 1.5 litres of fluid per day. They have had 750ml. How much more do they need?', 'short_answer', null, 'Numeracy', 10, '750', 1.0, 'A client needs 1.5 litres of fluid per day. They have had 750ml. How much more do they need?', 'short_answer', 'Numeracy', '750', 1.0, 'Fluid balance calculations', 2),
  ('q-c2c-n2', 'prod-cert2-community', 'ver-cert2-community-v1', 'Blood pressure reading is 120/80. Is this within normal range (90-120 / 60-80)?', 'true_false', '["True", "False"]', 'Numeracy', 11, 'True', 1.0, 'Blood pressure reading is 120/80. Is this within normal range (90-120 / 60-80)?', 'true_false', 'Numeracy', 'True', 1.0, 'Interprets vital signs', 2),
  ('q-c2c-n3', 'prod-cert2-community', 'ver-cert2-community-v1', 'Medication is given every 6 hours. If the last dose was at 2pm, when is the next dose?', 'short_answer', null, 'Numeracy', 12, '8pm', 1.0, 'Medication is given every 6 hours. If the last dose was at 2pm, when is the next dose?', 'short_answer', 'Numeracy', '8pm', 1.0, 'Time calculations for medication', 2),
  ('q-c2c-n4', 'prod-cert2-community', 'ver-cert2-community-v1', 'A client weighs 65kg. Their healthy weight range is 60-70kg. Are they in range?', 'true_false', '["True", "False"]', 'Numeracy', 13, 'True', 1.0, 'A client weighs 65kg. Their healthy weight range is 60-70kg. Are they in range?', 'true_false', 'Numeracy', 'True', 1.0, 'Weight monitoring', 2),
  -- Digital Literacy
  ('q-c2c-d1', 'prod-cert2-community', 'ver-cert2-community-v1', 'How do you enter a progress note into the electronic care system?', 'multiple_choice', '["Don''t use it", "Log in, find client, enter note, save", "Delete old notes", "Share password"]', 'Digital Literacy', 14, 'Log in, find client, enter note, save', 1.0, 'How do you enter a progress note into the electronic care system?', 'multiple_choice', 'Digital Literacy', 'Log in, find client, enter note, save', 1.0, 'Uses care software', 2),
  ('q-c2c-d2', 'prod-cert2-community', 'ver-cert2-community-v1', 'Why is it important to log out of the care system when finished?', 'multiple_choice', '["It''s not important", "To protect client privacy and security", "To annoy colleagues", "To break the system"]', 'Digital Literacy', 15, 'To protect client privacy and security', 1.0, 'Why is it important to log out of the care system when finished?', 'multiple_choice', 'Digital Literacy', 'To protect client privacy and security', 1.0, 'Understands digital privacy', 2);

-- ============================================
-- Step 9: Certificate III Community Services (ACSF Level 3)
-- ============================================
INSERT INTO questions (question_id, product_id, version_id, text, type, options, domain, order_index, correct_response, weight, question_text, question_type, acsf_domain, correct_answer, points_possible, acsf_skill, acsf_level) VALUES
  -- Reading
  ('q-c3c-r1', 'prod-cert3-community', 'ver-cert3-community-v1', 'Interpret this aged care standard: "Organisations must have systems to prevent and respond to abuse". What is required?', 'short_answer', null, 'Reading', 1, 'Systems for preventing abuse, responding to abuse reports, and protecting clients must be implemented', 1.0, 'Interpret this aged care standard: "Organisations must have systems to prevent and respond to abuse". What is required?', 'short_answer', 'Reading', 'Systems for preventing abuse, responding to abuse reports, and protecting clients must be implemented', 1.0, 'Interprets compliance requirements', 3),
  ('q-c3c-r2', 'prod-cert3-community', 'ver-cert3-community-v1', 'Review a client care plan and identify the specific support needs for someone with dementia.', 'short_answer', null, 'Reading', 2, 'Needs routine, memory aids, gentle redirection, familiar environment, and patience with repetition', 1.0, 'Review a client care plan and identify the specific support needs for someone with dementia.', 'short_answer', 'Reading', 'Needs routine, memory aids, gentle redirection, familiar environment, and patience with repetition', 1.0, 'Analyses care requirements', 3),
  ('q-c3c-r3', 'prod-cert3-community', 'ver-cert3-community-v1', 'Compare two medication administration policies and identify key differences in documentation requirements.', 'short_answer', null, 'Reading', 3, 'Policy A requires single signature, Policy B requires double-checking and two signatures for high-risk medications', 1.0, 'Compare two medication administration policies and identify key differences in documentation requirements.', 'short_answer', 'Reading', 'Policy A requires single signature, Policy B requires double-checking and two signatures for high-risk medications', 1.0, 'Compares policies', 3),
  ('q-c3c-r4', 'prod-cert3-community', 'ver-cert3-community-v1', 'Based on the medication chart, when is the client''s pain medication due and what is the maximum daily dose?', 'short_answer', null, 'Reading', 4, 'Next dose due at 6pm, maximum 8 tablets in 24 hours with 4-hour intervals between doses', 1.0, 'Based on the medication chart, when is the client''s pain medication due and what is the maximum daily dose?', 'short_answer', 'Reading', 'Next dose due at 6pm, maximum 8 tablets in 24 hours with 4-hour intervals between doses', 1.0, 'Interprets medication schedules', 3),
  -- Writing
  ('q-c3c-w1', 'prod-cert3-community', 'ver-cert3-community-v1', 'Write a comprehensive incident report for a medication error including what happened, contributing factors, and prevention strategies.', 'short_answer', null, 'Writing', 5, 'Medication given 2 hours late due to staff distraction during handover. Contributing factors: interruptions, no checklist. Prevention: Implement no-interruption zones, use medication administration checklist, additional staff training.', 1.0, 'Write a comprehensive incident report for a medication error including what happened, contributing factors, and prevention strategies.', 'short_answer', 'Writing', 'Medication given 2 hours late due to staff distraction during handover. Contributing factors: interruptions, no checklist. Prevention: Implement no-interruption zones, use medication administration checklist, additional staff training.', 1.0, 'Writes detailed incident reports', 3),
  ('q-c3c-w2', 'prod-cert3-community', 'ver-cert3-community-v1', 'Document a client''s behavioral changes including triggers, interventions attempted, and outcomes.', 'short_answer', null, 'Writing', 6, 'Client became agitated at 3pm (trigger: loud noise from construction). Interventions: moved to quiet room, offered preferred activity, used calm voice. Outcome: Settled within 20 minutes, participated in activity.', 1.0, 'Document a client''s behavioral changes including triggers, interventions attempted, and outcomes.', 'short_answer', 'Writing', 'Client became agitated at 3pm (trigger: loud noise from construction). Interventions: moved to quiet room, offered preferred activity, used calm voice. Outcome: Settled within 20 minutes, participated in activity.', 1.0, 'Writes behavioral observations', 3),
  ('q-c3c-w3', 'prod-cert3-community', 'ver-cert3-community-v1', 'Prepare a case note for a multidisciplinary team meeting about a client''s declining mobility.', 'short_answer', null, 'Writing', 7, 'Client mobility has declined over 3 weeks. Now requires frame for all transfers. Falls risk increased. Recommend: physiotherapy assessment, equipment review, updated care plan, family meeting.', 1.0, 'Prepare a case note for a multidisciplinary team meeting about a client''s declining mobility.', 'short_answer', 'Writing', 'Client mobility has declined over 3 weeks. Now requires frame for all transfers. Falls risk increased. Recommend: physiotherapy assessment, equipment review, updated care plan, family meeting.', 1.0, 'Writes professional case notes', 3),
  -- Oral Communication
  ('q-c3c-o1', 'prod-cert3-community', 'ver-cert3-community-v1', 'How would you explain to a family member that their loved one needs to move to higher-level care?', 'short_answer', null, 'Oral Communication', 8, 'Speak privately, explain observed changes in care needs with examples, discuss available options, listen to concerns, involve case manager, provide written information and time to decide.', 1.0, 'How would you explain to a family member that their loved one needs to move to higher-level care?', 'short_answer', 'Oral Communication', 'Speak privately, explain observed changes in care needs with examples, discuss available options, listen to concerns, involve case manager, provide written information and time to decide.', 1.0, 'Delivers sensitive information', 3),
  ('q-c3c-o2', 'prod-cert3-community', 'ver-cert3-community-v1', 'You need to handover important client information to the night shift. What should you include?', 'multiple_choice', '["Just say everything is fine", "Current condition, any changes, care requirements, medications due, concerns to monitor", "Nothing, they can read the notes", "Only problems"]', 'Oral Communication', 9, 'Current condition, any changes, care requirements, medications due, concerns to monitor', 1.0, 'You need to handover important client information to the night shift. What should you include?', 'multiple_choice', 'Oral Communication', 'Current condition, any changes, care requirements, medications due, concerns to monitor', 1.0, 'Provides comprehensive handover', 3),
  -- Numeracy
  ('q-c3c-n1', 'prod-cert3-community', 'ver-cert3-community-v1', 'Calculate fluid balance: Input 1200ml oral, 500ml IV. Output 900ml urine, 200ml vomit. What is the balance?', 'short_answer', null, 'Numeracy', 10, '600', 1.0, 'Calculate fluid balance: Input 1200ml oral, 500ml IV. Output 900ml urine, 200ml vomit. What is the balance?', 'short_answer', 'Numeracy', '600', 1.0, 'Fluid balance calculations', 3),
  ('q-c3c-n2', 'prod-cert3-community', 'ver-cert3-community-v1', 'A medication dose is 0.5mg per kg body weight. Client weighs 70kg. What is the dose?', 'short_answer', null, 'Numeracy', 11, '35', 1.0, 'A medication dose is 0.5mg per kg body weight. Client weighs 70kg. What is the dose?', 'short_answer', 'Numeracy', '35', 1.0, 'Weight-based dosage calculations', 3),
  ('q-c3c-n3', 'prod-cert3-community', 'ver-cert3-community-v1', 'Staff-to-client ratio must be 1:4. You have 18 clients on shift. How many staff needed?', 'short_answer', null, 'Numeracy', 12, '5', 1.0, 'Staff-to-client ratio must be 1:4. You have 18 clients on shift. How many staff needed?', 'short_answer', 'Numeracy', '5', 1.0, 'Ratio calculations', 3),
  ('q-c3c-n4', 'prod-cert3-community', 'ver-cert3-community-v1', 'A client''s pain score was 8/10 yesterday, 6/10 this morning, and 4/10 now. What is the trend?', 'multiple_choice', '["Increasing", "Decreasing", "Stable", "Unknown"]', 'Numeracy', 13, 'Decreasing', 1.0, 'A client''s pain score was 8/10 yesterday, 6/10 this morning, and 4/10 now. What is the trend?', 'multiple_choice', 'Numeracy', 'Decreasing', 1.0, 'Interprets trends in data', 3),
  -- Digital Literacy
  ('q-c3c-d1', 'prod-cert3-community', 'ver-cert3-community-v1', 'Which system would you use to document client care, track medications, and generate reports?', 'multiple_choice', '["Paper only", "Electronic health record system", "Personal notebook", "Text messages"]', 'Digital Literacy', 14, 'Electronic health record system', 1.0, 'Which system would you use to document client care, track medications, and generate reports?', 'multiple_choice', 'Digital Literacy', 'Electronic health record system', 1.0, 'Uses specialized care software', 3),
  ('q-c3c-d2', 'prod-cert3-community', 'ver-cert3-community-v1', 'How would you securely share a confidential client report with the doctor?', 'multiple_choice', '["Email to anyone", "Use secure portal or encrypted email as per policy", "Post it publicly", "Shout across the room"]', 'Digital Literacy', 15, 'Use secure portal or encrypted email as per policy', 1.0, 'How would you securely share a confidential client report with the doctor?', 'multiple_choice', 'Digital Literacy', 'Use secure portal or encrypted email as per policy', 1.0, 'Maintains digital confidentiality', 3);

-- ============================================
-- Step 10: Certificate IV Community Services (ACSF Level 4)
-- ============================================
INSERT INTO questions (question_id, product_id, version_id, text, type, options, domain, order_index, correct_response, weight, question_text, question_type, acsf_domain, correct_answer, points_possible, acsf_skill, acsf_level) VALUES
  -- Reading
  ('q-c4c-r1', 'prod-cert4-community', 'ver-cert4-community-v1', 'Critically analyse this policy on restraint use. Identify potential ethical and legal issues.', 'short_answer', null, 'Reading', 1, 'Policy lacks informed consent procedures, doesn''t specify least restrictive options, missing review timeframes. Legal risks include human rights violations and duty of care breaches.', 1.0, 'Critically analyse this policy on restraint use. Identify potential ethical and legal issues.', 'short_answer', 'Reading', 'Policy lacks informed consent procedures, doesn''t specify least restrictive options, missing review timeframes. Legal risks include human rights violations and duty of care breaches.', 1.0, 'Critically analyses policy', 4),
  ('q-c4c-r2', 'prod-cert4-community', 'ver-cert4-community-v1', 'Interpret the Aged Care Quality Standards to determine compliance requirements for clinical care.', 'short_answer', null, 'Reading', 2, 'Standard 3 requires clinical care and services to optimize health, evidence-based practice, medication management, and clinical governance systems.', 1.0, 'Interpret the Aged Care Quality Standards to determine compliance requirements for clinical care.', 'short_answer', 'Reading', 'Standard 3 requires clinical care and services to optimize health, evidence-based practice, medication management, and clinical governance systems.', 1.0, 'Interprets regulatory standards', 4),
  ('q-c4c-r3', 'prod-cert4-community', 'ver-cert4-community-v1', 'Compare palliative care approaches in three different care models and evaluate effectiveness.', 'short_answer', null, 'Reading', 3, 'Medical model focuses on symptom management, social model emphasizes quality of life and dignity, holistic model integrates both plus spiritual and family support. Holistic shows best outcomes.', 1.0, 'Compare palliative care approaches in three different care models and evaluate effectiveness.', 'short_answer', 'Reading', 'Medical model focuses on symptom management, social model emphasizes quality of life and dignity, holistic model integrates both plus spiritual and family support. Holistic shows best outcomes.', 1.0, 'Evaluates care models', 4),
  ('q-c4c-r4', 'prod-cert4-community', 'ver-cert4-community-v1', 'Review client assessment data and determine ACFI funding level based on complex care needs.', 'short_answer', null, 'Reading', 4, 'Based on ADL dependency, continence requirements, and complex health conditions, client qualifies for High ACFI funding category.', 1.0, 'Review client assessment data and determine ACFI funding level based on complex care needs.', 'short_answer', 'Reading', 'Based on ADL dependency, continence requirements, and complex health conditions, client qualifies for High ACFI funding category.', 1.0, 'Analyses assessment data', 4),
  -- Writing
  ('q-c4c-w1', 'prod-cert4-community', 'ver-cert4-community-v1', 'Develop a comprehensive care plan for a client with multiple chronic conditions including goals, interventions, and evaluation criteria.', 'short_answer', null, 'Writing', 5, 'Goals: Pain management, maintained mobility, nutrition optimization. Interventions: Medication review, physiotherapy, dietitian consult, regular monitoring. Evaluation: Pain scores, mobility assessments, weight tracking, quality of life measures. Review monthly.', 1.0, 'Develop a comprehensive care plan for a client with multiple chronic conditions including goals, interventions, and evaluation criteria.', 'short_answer', 'Writing', 'Goals: Pain management, maintained mobility, nutrition optimization. Interventions: Medication review, physiotherapy, dietitian consult, regular monitoring. Evaluation: Pain scores, mobility assessments, weight tracking, quality of life measures. Review monthly.', 1.0, 'Develops care plans', 4),
  ('q-c4c-w2', 'prod-cert4-community', 'ver-cert4-community-v1', 'Write a case study analysis for a quality improvement project addressing medication errors.', 'short_answer', null, 'Writing', 6, 'Analysis: 12 errors in 6 months, mainly during shift changes. Root causes: inadequate handover, distraction, no double-checking. Improvement: Implemented ISBAR handover tool, no-interruption medication times, electronic checking system. Results: 75% reduction in errors over 3 months.', 1.0, 'Write a case study analysis for a quality improvement project addressing medication errors.', 'short_answer', 'Writing', 'Analysis: 12 errors in 6 months, mainly during shift changes. Root causes: inadequate handover, distraction, no double-checking. Improvement: Implemented ISBAR handover tool, no-interruption medication times, electronic checking system. Results: 75% reduction in errors over 3 months.', 1.0, 'Writes analytical reports', 4),
  ('q-c4c-w3', 'prod-cert4-community', 'ver-cert4-community-v1', 'Prepare a policy submission on culturally safe care practices for diverse communities.', 'short_answer', null, 'Writing', 7, 'Policy must include: cultural competency training, interpreter services, culturally appropriate food, respect for religious practices, family involvement protocols, and feedback mechanisms. Regular audits required to ensure implementation.', 1.0, 'Prepare a policy submission on culturally safe care practices for diverse communities.', 'short_answer', 'Writing', 'Policy must include: cultural competency training, interpreter services, culturally appropriate food, respect for religious practices, family involvement protocols, and feedback mechanisms. Regular audits required to ensure implementation.', 1.0, 'Develops policy documents', 4),
  -- Oral Communication
  ('q-c4c-o1', 'prod-cert4-community', 'ver-cert4-community-v1', 'You are facilitating a family conference about end-of-life care decisions. What process should you follow?', 'short_answer', null, 'Oral Communication', 8, 'Establish private comfortable setting, introduce team members, review client''s condition and prognosis, discuss advance care planning, explore family wishes, address concerns, document decisions, arrange follow-up, provide written summary and support resources.', 1.0, 'You are facilitating a family conference about end-of-life care decisions. What process should you follow?', 'short_answer', 'Oral Communication', 'Establish private comfortable setting, introduce team members, review client''s condition and prognosis, discuss advance care planning, explore family wishes, address concerns, document decisions, arrange follow-up, provide written summary and support resources.', 1.0, 'Facilitates complex discussions', 4),
  ('q-c4c-o2', 'prod-cert4-community', 'ver-cert4-community-v1', 'How do you manage conflict between staff members regarding different care approaches?', 'multiple_choice', '["Ignore it", "Facilitate professional discussion using evidence-based practice, seek common ground, escalate if needed", "Take sides", "Fire everyone"]', 'Oral Communication', 9, 'Facilitate professional discussion using evidence-based practice, seek common ground, escalate if needed', 1.0, 'How do you manage conflict between staff members regarding different care approaches?', 'multiple_choice', 'Oral Communication', 'Facilitate professional discussion using evidence-based practice, seek common ground, escalate if needed', 1.0, 'Manages professional conflict', 4),
  -- Numeracy
  ('q-c4c-n1', 'prod-cert4-community', 'ver-cert4-community-v1', 'Calculate staffing costs: 15 staff, mix of RN ($45/hr), EN ($38/hr), AIN ($28/hr) for 24-hour coverage. 40% RN, 30% EN, 30% AIN. Daily cost?', 'short_answer', null, 'Numeracy', 10, '13680', 1.0, 'Calculate staffing costs: 15 staff, mix of RN ($45/hr), EN ($38/hr), AIN ($28/hr) for 24-hour coverage. 40% RN, 30% EN, 30% AIN. Daily cost?', 'short_answer', 'Numeracy', '13680', 1.0, 'Complex budget calculations', 4),
  ('q-c4c-n2', 'prod-cert4-community', 'ver-cert4-community-v1', 'Analyse falls data: 45 falls in Q1, 38 in Q2, 29 in Q3. What is the percentage reduction from Q1 to Q3?', 'short_answer', null, 'Numeracy', 11, '36', 1.0, 'Analyse falls data: 45 falls in Q1, 38 in Q2, 29 in Q3. What is the percentage reduction from Q1 to Q3?', 'short_answer', 'Numeracy', '36', 1.0, 'Statistical analysis', 4),
  ('q-c4c-n3', 'prod-cert4-community', 'ver-cert4-community-v1', 'Client-to-staff ratio target is 1:6 day, 1:10 night. Facility has 84 clients. Calculate staff needed for 24 hours.', 'short_answer', null, 'Numeracy', 12, '22', 1.0, 'Client-to-staff ratio target is 1:6 day, 1:10 night. Facility has 84 clients. Calculate staff needed for 24 hours.', 'short_answer', 'Numeracy', '22', 1.0, 'Workforce planning calculations', 4),
  ('q-c4c-n4', 'prod-cert4-community', 'ver-cert4-community-v1', 'Medication stock: 500 tablets used per month, 2-week lead time for orders. What is the minimum stock level with 20% buffer?', 'short_answer', null, 'Numeracy', 13, '300', 1.0, 'Medication stock: 500 tablets used per month, 2-week lead time for orders. What is the minimum stock level with 20% buffer?', 'short_answer', 'Numeracy', '300', 1.0, 'Inventory management', 4),
  -- Digital Literacy
  ('q-c4c-d1', 'prod-cert4-community', 'ver-cert4-community-v1', 'Which systems are needed to manage a comprehensive aged care service digitally?', 'multiple_choice', '["Just email", "Integrated EHR, rostering, medication management, billing, reporting, and compliance systems", "Paper files only", "Phone calls"]', 'Digital Literacy', 14, 'Integrated EHR, rostering, medication management, billing, reporting, and compliance systems', 1.0, 'Which systems are needed to manage a comprehensive aged care service digitally?', 'multiple_choice', 'Digital Literacy', 'Integrated EHR, rostering, medication management, billing, reporting, and compliance systems', 1.0, 'Manages complex digital systems', 4),
  ('q-c4c-d2', 'prod-cert4-community', 'ver-cert4-community-v1', 'How would you implement a new care documentation system across multiple teams?', 'short_answer', null, 'Digital Literacy', 15, 'Phased rollout: assess current systems, select appropriate software, pilot with one team, train super-users, provide ongoing support, gather feedback, refine processes, full implementation with continuous evaluation.', 1.0, 'How would you implement a new care documentation system across multiple teams?', 'short_answer', 'Digital Literacy', 'Phased rollout: assess current systems, select appropriate software, pilot with one team, train super-users, provide ongoing support, gather feedback, refine processes, full implementation with continuous evaluation.', 1.0, 'Implements digital change', 4);

-- ============================================
-- Migration Complete
-- ============================================
-- Total: 8 assessment products, 8 versions, 120 questions (15 per assessment)
-- Coverage: All ACSF domains across 4 AQF levels for both Trade and Community Services streams
